// bouldering grades
export const vGradeDropdownData = [
  { value: '', label: 'Choose a V-grade' },
  { value: 'vb', label: 'VB' },
  { value: 'v0', label: 'V0' },
  { value: 'v1', label: 'V1' },
  { value: 'v2', label: 'V2' },
  { value: 'v3', label: 'V3' },
  { value: 'v4', label: 'V4' },
  { value: 'v5', label: 'V5' },
  { value: 'v6', label: 'V6' },
  { value: 'v7', label: 'V7' },
  { value: 'v8', label: 'V8' },
  { value: 'v9', label: 'V9' },
  { value: 'v1', label: 'V10' },
  { value: 'v11', label: 'V11' },
  { value: 'v12', label: 'V12' },
  { value: 'v13', label: 'V13' },
  { value: 'v14', label: 'V14' },
  { value: 'v15', label: 'V15' },
  { value: 'v16', label: 'V16' },
  { value: 'v17', label: 'V17' },
];
export const fontGradeDropdownData = [
  { value: '', label: 'Choose a Font Grade' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
  { value: '5+', label: '5+' },
  { value: '6A/+', label: '6A/+' },
  { value: '6B/+', label: '6B/+' },
  { value: '6C/+', label: '6C/+' },
  { value: '7A', label: '7A' },
  { value: '7A+', label: '7A+' },
  { value: '7B/+', label: '7B/+' },
  { value: '7C', label: '7C' },
  { value: '7C+', label: '7C+' },
  { value: '8A', label: '8A' },
  { value: '8A+', label: '8A+' },
  { value: '8B', label: '8B' },
  { value: '8B+', label: '8B+' },
  { value: '8C', label: '8C' },
  { value: '8C+', label: '8C+' },
  { value: '9A', label: '9A' },
];
// sport/trad grades
export const ydsGradeDropdownData = [
  { value: '', label: 'Choose a YDS Grade' },
  { value: '5.0', label: '5.0' },
  { value: '5.1', label: '5.1' },
  { value: '5.2', label: '5.2' },
  { value: '5.3', label: '5.3' },
  { value: '5.4', label: '5.4' },
  { value: '5.5', label: '5.5' },
  { value: '5.6', label: '5.6' },
  { value: '5.7', label: '5.7' },
  { value: '5.8', label: '5.8' },
  { value: '5.9', label: '5.9' },
  { value: '5.10a', label: '5.10a' },
  { value: '5.10b', label: '5.10b' },
  { value: '5.10c', label: '5.10c' },
  { value: '5.10d', label: '5.10d' },
  { value: '5.11a', label: '5.11a' },
  { value: '5.11b', label: '5.11b' },
  { value: '5.11c', label: '5.11c' },
  { value: '5.11d', label: '5.11d' },
  { value: '5.12a', label: '5.12a' },
  { value: '5.12b', label: '5.12b' },
  { value: '5.12c', label: '5.12c' },
  { value: '5.12d', label: '5.12d' },
  { value: '5.13a', label: '5.13a' },
  { value: '5.13d', label: '5.13b' },
  { value: '5.13c', label: '5.13c' },
  { value: '5.13d', label: '5.13d' },
  { value: '5.14a', label: '5.14a' },
  { value: '5.14b', label: '5.14b' },
  { value: '5.14c', label: '5.14c' },
  { value: '5.14d', label: '5.14d' },
  { value: '5.15a', label: '5.15a' },
  { value: '5.15b', label: '5.15b' },
  { value: '5.15c', label: '5.15c' },
  { value: '5.15d', label: '5.15d' },
];
export const frenchSportGradeDropdownData = [
  { value: '', label: 'Choose a French Sport Grade' },
  { value: '2-', label: '3' },
  { value: '2', label: '4' },
  { value: '3', label: '5' },
  { value: '3+', label: '5+' },
  { value: '4a', label: '6A/+' },
  { value: '4b', label: '6B/+' },
  { value: '4c', label: '6C/+' },
  { value: '5a', label: '7A' },
  { value: '5b', label: '7A+' },
  { value: '5c', label: '7B/+' },
  { value: '6a', label: '7C' },
  { value: '6a+', label: '7C+' },
  { value: '6b', label: '8A' },
  { value: '6b+', label: '8A+' },
  { value: '6c', label: '8B' },
  { value: '6c+', label: '8B+' },
  { value: '7a', label: '8C' },
  { value: '7a+', label: '8C+' },
  { value: '7b', label: '9A' },
  { value: '7b+', label: '9A' },
  { value: '7c', label: '9A' },
  { value: '7c+', label: '9A' },
  { value: '8a', label: '9A' },
  { value: '8a+', label: '9A' },
  { value: '8b', label: '9A' },
  { value: '8b+', label: '9A' },
  { value: '8c', label: '9A' },
  { value: '8c+', label: '9A' },
  { value: '9a', label: '9A' },
  { value: '9a+', label: '9A' },
  { value: '9b', label: '9A' },
  { value: '9b+', label: '9A' },
  { value: '9c', label: '9A' },
  { value: '9b+', label: '9A' },
];
