export const gradingSystemDropdownData = [
  { value: 'Choose system', label: 'Choose System', selected: null },
  { value: 'V-Scale', label: 'V-Scale', selected: null },
  { value: 'Font', label: 'Font', selected: null },
  { value: 'Dankyu', label: 'Dankyu', selected: null },
];
export const ropeGradingSystemDropdownData = [
  { value: '', label: 'Choose a grading system', selected: null },
  { value: 'YDS', label: 'YDS', selected: null },
  { value: 'French', label: 'French', selected: null },
];
export const vGradeDropdownData = [
  { value: '', label: 'Choose a V-grade', selected: null },
  { value: 'vb', label: 'VB', selected: null },
  { value: 'v0', label: 'V0', selected: null },
  { value: 'v1', label: 'V1', selected: null },
  { value: 'v2', label: 'V2', selected: null },
  { value: 'v3', label: 'V3', selected: null },
  { value: 'v4', label: 'V4', selected: null },
  { value: 'v5', label: 'V5', selected: null },
  { value: 'v6', label: 'V6', selected: null },
  { value: 'v7', label: 'V7', selected: null },
  { value: 'v8', label: 'V8', selected: null },
  { value: 'v9', label: 'V9', selected: null },
  { value: 'v1', label: 'V10', selected: null },
  { value: 'v11', label: 'V11', selected: null },
  { value: 'v12', label: 'V12', selected: null },
  { value: 'v13', label: 'V13', selected: null },
  { value: 'v14', label: 'V14', selected: null },
  { value: 'v15', label: 'V15', selected: null },
  { value: 'v16', label: 'V16', selected: null },
  { value: 'v17', label: 'V17', selected: null },
];
export const fontGradeDropdownData = [
  { value: '', label: 'Choose a Font Grade', selected: null },
  { value: '3', label: '3', selected: null },
  { value: '4', label: '4', selected: null },
  { value: '5', label: '5', selected: null },
  { value: '5+', label: '5+', selected: null },
  { value: '6A/+', label: '6A/+', selected: null },
  { value: '6B/+', label: '6B/+', selected: null },
  { value: '6C/+', label: '6C/+', selected: null },
  { value: '7A', label: '7A', selected: null },
  { value: '7A+', label: '7A+', selected: null },
  { value: '7B/+', label: '7B/+', selected: null },
  { value: '7C', label: '7C', selected: null },
  { value: '7C+', label: '7C+', selected: null },
  { value: '8A', label: '8A', selected: null },
  { value: '8A+', label: '8A+', selected: null },
  { value: '8B', label: '8B', selected: null },
  { value: '8B+', label: '8B+', selected: null },
  { value: '8C', label: '8C', selected: null },
  { value: '8C+', label: '8C+', selected: null },
  { value: '9A', label: '9A', selected: null },
];
export const ydsGradeDropdownData = [
  { value: '', label: 'Choose a YDS Grade', selected: null },
  { value: '5.0', label: '5.0', selected: null },
  { value: '5.1', label: '5.1', selected: null },
  { value: '5.2', label: '5.2', selected: null },
  { value: '5.3', label: '5.3', selected: null },
  { value: '5.4', label: '5.4', selected: null },
  { value: '5.5', label: '5.5', selected: null },
  { value: '5.6', label: '5.6', selected: null },
  { value: '5.7', label: '5.7', selected: null },
  { value: '5.8', label: '5.8', selected: null },
  { value: '5.9', label: '5.9', selected: null },
  { value: '5.10a', label: '5.10a', selected: null },
  { value: '5.10b', label: '5.10b', selected: null },
  { value: '5.10c', label: '5.10c', selected: null },
  { value: '5.10d', label: '5.10d', selected: null },
  { value: '5.11a', label: '5.11a', selected: null },
  { value: '5.11b', label: '5.11b', selected: null },
  { value: '5.11c', label: '5.11c', selected: null },
  { value: '5.11d', label: '5.11d', selected: null },
  { value: '5.12a', label: '5.12a', selected: null },
  { value: '5.12b', label: '5.12b', selected: null },
  { value: '5.12c', label: '5.12c', selected: null },
  { value: '5.12d', label: '5.12d', selected: null },
  { value: '5.13a', label: '5.13a', selected: null },
  { value: '5.13d', label: '5.13b', selected: null },
  { value: '5.13c', label: '5.13c', selected: null },
  { value: '5.13d', label: '5.13d', selected: null },
  { value: '5.14a', label: '5.14a', selected: null },
  { value: '5.14b', label: '5.14b', selected: null },
  { value: '5.14c', label: '5.14c', selected: null },
  { value: '5.14d', label: '5.14d', selected: null },
  { value: '5.15a', label: '5.15a', selected: null },
  { value: '5.15b', label: '5.15b', selected: null },
  { value: '5.15c', label: '5.15c', selected: null },
  { value: '5.15d', label: '5.15d', selected: null },
];
export const frenchSportGradeDropdownData = [
  { value: '', label: 'Choose a French Sport Grade', selected: null },
  { value: '2-', label: '3', selected: null },
  { value: '2', label: '4', selected: null },
  { value: '3', label: '5', selected: null },
  { value: '3+', label: '5+', selected: null },
  { value: '4a', label: '6A/+', selected: null },
  { value: '4b', label: '6B/+', selected: null },
  { value: '4c', label: '6C/+', selected: null },
  { value: '5a', label: '7A', selected: null },
  { value: '5b', label: '7A+', selected: null },
  { value: '5c', label: '7B/+', selected: null },
  { value: '6a', label: '7C', selected: null },
  { value: '6a+', label: '7C+', selected: null },
  { value: '6b', label: '8A', selected: null },
  { value: '6b+', label: '8A+', selected: null },
  { value: '6c', label: '8B', selected: null },
  { value: '6c+', label: '8B+', selected: null },
  { value: '7a', label: '8C', selected: null },
  { value: '7a+', label: '8C+', selected: null },
  { value: '7b', label: '9A', selected: null },
  { value: '7b+', label: '9A', selected: null },
  { value: '7c', label: '9A', selected: null },
  { value: '7c+', label: '9A', selected: null },
  { value: '8a', label: '9A', selected: null },
  { value: '8a+', label: '9A', selected: null },
  { value: '8b', label: '9A', selected: null },
  { value: '8b+', label: '9A', selected: null },
  { value: '8c', label: '9A', selected: null },
  { value: '8c+', label: '9A', selected: null },
  { value: '9a', label: '9A', selected: null },
  { value: '9a+', label: '9A', selected: null },
  { value: '9b', label: '9A', selected: null },
  { value: '9b+', label: '9A', selected: null },
  { value: '9c', label: '9A', selected: null },
  { value: '9b+', label: '9A', selected: null },
];
